# Generated by Django 5.1 on 2024-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_city', models.CharField(max_length=100)),
                ('from_time', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
