# Generated by Django 5.1 on 2024-09-01 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('count_seat', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'trains',
                'db_table': 'trains',
            },
        ),
        migrations.CreateModel(
            name='TrainRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('to_time', models.DateTimeField(blank=True, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('from_city', models.ForeignKey(blank=True, db_column='from_city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cities')),
                ('to_city', models.ForeignKey(blank=True, db_column='to_city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainroutes_to_city_set', to='api.cities')),
                ('train', models.ForeignKey(blank=True, db_column='train', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.trains')),
            ],
            options={
                'verbose_name_plural': 'train_routes',
                'db_table': 'train_routes',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('train_route', models.ForeignKey(blank=True, db_column='train_route', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.trainroutes')),
            ],
            options={
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
            },
        ),
    ]
