openapi: 3.0.3
info:
  title: Train Service - OpenAPI 3.0
  description: |-
    This is a sample Train Service Server based on the OpenAPI 3.0 specification.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://127.0.0.1:8000/
tags:
  - name: train_routes
    description: Everything about train routes
paths:
  /train_routes:
    get:
        tags:
          - train_routes
        summary: Get all train routes
        description: Get all train routes
        operationId: getTrainRoutes
        parameters:
          - name: from_city
            in: query
            schema:
              type: string
          - name: from_time
            in: query
            schema:
              type: string
          - name: to_city
            in: query
            schema:
              type: string
          - name: to_time
            in: query
            schema:
              type: string
          - name: cost
            in: query
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                    $ref: '#/components/schemas/TrainRoutes'          
              application/xml:
                schema:
                    $ref: '#/components/schemas/TrainRoutes'
    post:
        tags:
          - train_routes
        summary: Add a new train route
        description: Add a new train route
        operationId: addTrainRoute
        requestBody:
          description: Create a new train route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainRoute'
            application/xml:
              schema:
                $ref: '#/components/schemas/TrainRoute'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/TrainRoute'
          required: true
        responses:
          '201':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TrainRoute' 
              application/xml:
                schema:
                  $ref: '#/components/schemas/TrainRoute'
          '400':
            description: Invalid input
    put:
      tags:
        - train_routes
      summary: Update an existing train route
      description: Update an existing train route by Id
      operationId: updateTrainRoute
      requestBody:
        description: Update an existing train route
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainRoute' 
          application/xml:
            schema:
              $ref: '#/components/schemas/TrainRoute' 
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TrainRoute' 
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainRoute'     
            application/xml:
              schema:
                $ref: '#/components/schemas/TrainRoute' 
        '400':
          description: Invalid input
        '404':
          description: Train route not found
  /train_routes/{id}:
    get:
      tags:
        - train_routes
      summary: Find train route by ID
      description: Returns a single train route
      operationId: getTrainRouteById
      parameters:
        - name: id
          in: path
          description: ID of train route to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainRoute'         
            application/xml:
              schema:
                $ref: '#/components/schemas/TrainRoute'
        '404':
          description: Invalid ID supplied
    delete:
      tags:
        - train_routes
      summary: Deletes a train route
      description: delete a train route
      operationId: deleteTrainRoute
      parameters:
        - name: id
          in: path
          description: Train route id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
            description: successful operation
        '404':
          description: Invalid ID supplied
components:
  schemas:
    TrainRoute:
      required:
          - id
          - from_city
          - from_time
          - to_city
          - to_time
          - cost
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        from_city:
          type: string
          example: Тверь
        from_time:
          type: string
          example: 19.08.2024 20:24
        to_city:
          type: string
          example: Санкт-Петербург
        to_time:
          type: string
          example: 20.08.2024 3:58
        cost:
          type: integer
          example: 3700
      xml:
        name: trainRoute
    TrainRoutes:
      type: array
      items: 
        $ref: '#/components/schemas/TrainRoute'
      xml:
        wrapped: true